<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Bootstrap -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional Bootstrap theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Font Awesome -->
<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">-->

<!-- Favicon -->
<link rel="apple-touch-icon" sizes="76x76" href="/images/favicon-76.png">
<link rel="apple-touch-icon" sizes="120x120" href="/images/favicon-120.png">
<link rel="apple-touch-icon" sizes="152x152" href="/images/favicon-152.png">
<link rel="icon" sizes="196x196" href="/images/favicon-196.png">
<link rel="icon" type="image/x-icon" href="/images/favicon.ico">

<!-- jQWidgets Theme -->
<link rel="stylesheet" href="http://www.jqwidgets.com/public/jqwidgets/styles/jqx.base.css" type="text/css">
<link rel="stylesheet" href="http://www.jqwidgets.com/public/jqwidgets/styles/jqx.bootstrap.css" type="text/css">

<!-- Leaflet & Plugins -->
<link rel="stylesheet" href="/css/leaflet.css">
<link rel="stylesheet" href="/css/fontello.css">
<link rel="stylesheet" href="/css/go-leaflet.css">
<link rel="stylesheet" href="/css/L.Control.MousePosition.css">
<link rel="stylesheet" href="/css/app.css">

<title>{{.title}}</title>
