<div role="navigation" class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class="navbar-icon-container">
        <a id="nav-btn" class="navbar-icon pull-right visible-xs" href="#"><i class="fa fa-bars fa-lg white"></i></a>
        <a id="sidebar-toggle-btn" class="navbar-icon pull-right visible-xs" href="#"><i class="fa fa-search fa-lg white"></i></a>
      </div>
      <a href="#" class="navbar-brand">{{.title}}</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a id="about-btn" data-target=".navbar-collapse.in" data-toggle="collapse" href="#"><i class="fa fa-question-circle white"></i>&nbsp;&nbsp;A propos</a></li>
        <li><a id="about-btn" data-target=".navbar-collapse.in" data-toggle="collapse" href="/markers"><i class="fa fa-plus white"></i>&nbsp;&nbsp;Ajouter des marqueurs</a></li>
        <li><a id="about-btn" data-target=".navbar-collapse.in" data-toggle="collapse" href="/markers"><i class="fa icon-cog-alt white"></i>&nbsp;&nbsp;Gérer les marqueurs</a></li>
        <li><a id="full-extent-btn" data-target=".navbar-collapse.in" data-toggle="collapse" href="#"><i class="fa fa-arrows-alt white"></i>&nbsp;&nbsp;Réinitialiser le zoom</a></li>
      </ul>
    </div><!--/.navbar-collapse -->
  </div>
</div><!--/.navigation -->
